parameter_defaults:
  CephAnsiblePlaybookVerbosity: 1
  CephAnsibleDisksConfig:
    devices:
      - /dev/vdb
      - /dev/vdc
    dedicated_devices:
      - /dev/vdd
      - /dev/vdd

  CephAnsibleExtraConfig:
    osd_scenario: non-collocated
    osd_objectstore: filestore
