heat_template_version: 2014-10-16

description: > 
  Extra hostname configuration

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: config_motd}

  config_motd:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
        #!/bin/bash
        echo "Welcome to myCloud" >> /etc/motd
        echo centos |  passwd --stdin centos

outputs:
  OS::stack_id:
    value: {get_resource: userdata}
